### ISSUE TITLE
Miscellaneous Install, Start, Rebuild Issues 

### ISSUE THREAD

**Issue by datamike** [stanlemon/salesforce-explorer#2]
@stanlemon - Thank you for this great project!

I'm fairly new to Node.js, and I wasn't quite able to get it to run on a Windows (7) machine.
I'm running Node version '8.9.4' .

I don't care that much about packaging the electron app (although that sounds very cool!) - I would like to have a working 'npm start' command.  Some errors:

**1.**  The install command at first threw a few messages concerning deprecated packages that should be updated (coffeescript, pug, jstransformer, e.g.).   I installed those dependencies using npm install, and that made those messages go away.

**2.**  On 'npm rebuild' and 'npm start', I saw the below error a few times.  It looks like it's trying to set or reference an Environment Variable.

> salesforce-explorer@0.1.0 start C:\DevTools\SFDC-Explorer
> NODE_ENV=development electron main.js

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! salesforce-explorer@0.1.0 start: `NODE_ENV=development electron main.js
`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the salesforce-explorer@0.1.0 start script.

**3.**   But I also got the rebuild to complete:

C:\DevTools\SFDC-Explorer>npm run rebuild

> salesforce-explorer@0.1.0 rebuild C:\DevTools\SFDC-Explorer
> electron-rebuild

√ Rebuild Complete

C:\DevTools\SFDC-Explorer>npm run package

> salesforce-explorer@0.1.0 package C:\DevTools\SFDC-Explorer
> electron-packager . 'Salesforce Explorer' --overwrite --out=release --asar=true

Packaging app for platform win32 x64 using electron v1.8.2
Wrote new app to release\'Salesforce-win32-x64

**4.**  This was something I ran into when I ran install again.  I looked in the directory [C:\DevTools\SFDC-Explorer\node_modules\keytar\build\keytar.vcxproj] to see if that Visual C++ project file was there, and it was not - so it looks like a path problem somewhere.

C:\DevTools\SFDC-Explorer>npm install

> keytar@4.1.0 install C:\DevTools\SFDC-Explorer\node_modules\keytar
> node-gyp rebuild

C:\DevTools\SFDC-Explorer\node_modules\keytar>if not defined npm_config_node_gyp
 (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node
-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node _**"C:
\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js"**_ re
build )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\DevTools\SFDC-Explorer\node_modules\keytar\build\keytar.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:198:12)

Thanks again!  Michael

**Comment by stanlemon** [comment]
With the start command, inside of package.json under the start section try removing NODE_ENV=development from the beginning of it so that it’s just electron main.js Try that and let me know if that works.

I have never tried this on Windows, so I’m flying a little blind here. I am suspicious that maybe the packaging toolset I’m using has a bug. I don’t know off hand how big of a deal it is to upgrade, but that can be looked into. The keytar module should work though, and if we can get the app to start on windows that would probably zero in on the packaging library.

**Comment by datamike** [comment]
Yes, that gets things moving a bit better when I run 'npm start'.  But the error that gets thrown now is "Cannot find module keytar."

C:\DevTools\SFDC-Explorer>npm start

> salesforce-explorer@0.1.0 start C:\DevTools\SFDC-Explorer
> electron main.js

App threw an error during load
Error: Cannot find module 'keytar'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (C:\DevTools\SFDC-Explorer\node_modules\
electron\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\DevTools\SFDC-Explorer\main.js:4:16)
    at Object.<anonymous> (C:\DevTools\SFDC-Explorer\main.js:220:3)
    at Module._compile (module.js:569:30)
    at Object.require.extensions.(anonymous function) [as .js] (C:\DevTools\SFDC
-Explorer\node_modules\electron-compile\lib\require-hook.js:77:14)
    at Module.load (module.js:503:32)

**Comment by stanlemon** [comment]
Is there a keytar folder under node_modules?

**Comment by datamike** [comment]
No, there is no such folder within the project folders.

**Comment by stanlemon** [comment]
Can you try just doing: `npm install keytar@4.1 --save` and paste any output if it fails?

**Comment by datamike** [comment]
Here it is.   Looks like I need to install the Windows SDK version 8.1.  But another interesting thing is that there still is not a folder '..\node_modules\keytar'.

C:\DevTools\SFDC-Explorer>npm install keytar@4.1 --save

> keytar@4.1.0 install C:\DevTools\SFDC-Explorer\node_modules\keytar
> node-gyp rebuild

C:\DevTools\SFDC-Explorer\node_modules\keytar>if not defined npm_config_node_gyp
 (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node
-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:
\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" re
build )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformTo
olsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 w
as not found. Install the required version of Windows SDK or change the SDK ver
sion in the project property pages or by right-clicking the solution and select
ing "Retarget solution". [C:\DevTools\SFDC-Explorer\node_modules\keytar\build\k
eytar.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:198:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\DevTools\SFDC-Explorer\node_modules\keytar
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN The package babel-cli is included as both a dev and production dependen
cy.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fse
vents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keytar@4.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keytar@4.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

**Comment by datamike** [comment]
I just looked at the last of the npm warnings.  fsevents@1.1.3 is apparently not supported for Win32:

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fse
vents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}

**Comment by stanlemon** [comment]
Gotcha, so this is really out of my wheelhouse as I'm not a windows guy.  I'm grasping at straws here.

Try `npm install --no-optional keytar@4.1` and see if that gets past the fsevents dependency. 🤞

**Comment by datamike** [comment]
@stanlemon Thanks for your quick responses.  Looks like fsevents is no-go on Windows (and Linux, for that matter).

https://www.npmjs.com/package/fsevents indicates, however, that fsevents is only for OS X:

> The FSEvents API in OS X allows applications to register for notifications of changes to a given directory tree. It is a very fast and lightweight alternative to kqueue.
> 
> This is a low-level library. For a cross-compatible file watching module that uses fsevents, check out [Chokidar](https://www.npmjs.com/package/chokidar).

Here's the output of 'npm install --no-optional keytar @4.1 :

`gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:198:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\DevTools\SFDC-Explorer\node_modules\keytar
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN The package babel-cli is included as both a dev and production dependen
cy.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fse
vents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keytar@4.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keytar@4.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mboyle9\AppData\Roaming\npm-cache\_logs\2018-02-22T15_45_4
9_893Z-debug.log
`

**Comment by stanlemon** [comment]
Alright, so just to be clear I am not specifying fsevents, it comes through the dependency tree which I have no control over.

Your latest error makes me think the rebuild process might have put thinks in a weird state.

I would delete the node_modules folder and run npm install --no-optional 

Just to see if we can get a full install run and maybe skip that fsevents dep.

**Comment by datamike** [comment]
Thanks - pls know that I appreciate your help with this.   
Wow, there was 300 MB worth of data in that folder.

```
prebuild-install info renaming to @ C:\..\Roaming\npm-cache\_
prebuilds\https-github.com-atom-node-keytar-releases-download-v4.2.0-keytar-v4.2
.0-node-v57-win32-x64.tar.gz
prebuild-install info unpacking @ C:\..\Roaming\npm-cache\_pr
ebuilds\https-github.com-atom-node-keytar-releases-download-v4.2.0-keytar-v4.2.0
-node-v57-win32-x64.tar.gz
prebuild-install info unpack resolved to C:\..\SFDC-Explorer\node_modules\
keytar\build\Release\keytar.node
prebuild-install info unpack required C:\..\SFDC-Explorer\node_modules\key
tar\build\Release\keytar.node successfully
prebuild-install info install Successfully installed prebuilt binary!

> electron@1.8.2 postinstall C:\DevTools\SFDC-Explorer\node_modules\electron
> node install.js

npm WARN The package babel-cli is included as both a dev and production dependen
cy.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fse
vents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)

added 953 packages in 133.249s

```

When I did npm run, I got the message below.  Not quite all the way there, but much better! 
```

C:\DevTools\SFDC-Explorer>npm run start

> salesforce-explorer@0.1.0 start C:\DevTools\SFDC-Explorer
> electron main.js


App threw an error during load
Error: The system cannot find message text for message number 0x%1 in the messag
e file for %2.
\\?\C:\..\SFDC-Explorer\node_modules\keytar\build\Release\keytar.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)

    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\..\SFDC-Explorer\node_modules\keytar\lib\key
tar.js:1:169)
    at Object.<anonymous> (C:\..\SFDC-Explorer\node_modules\keytar\lib\key
tar.js:61:3)


```

I then ran rebuild and then start and got a slightly different message:

```
C:\..\SFDC-Explorer>npm run rebuild

> salesforce-explorer@0.1.0 rebuild C:\..\SFDC-Explorer
> electron-rebuild

√ Rebuild Complete

C:\..\SFDC-Explorer>npm start

> salesforce-explorer@0.1.0 start C:\..\SFDC-Explorer
> electron main.js


App threw an error during load
TypeError: electron.app.setAboutPanelOptions is not a function
    at Object.<anonymous> (C:\..\SFDC-Explorer\main.js:173:14)
    at Object.<anonymous> (C:\..\SFDC-Explorer\main.js:220:3)
    at Module._compile (module.js:569:30)
    at Object.require.extensions.(anonymous function) [as .js] (C:\..\SFDC
-Explorer\node_modules\electron-compile\lib\require-hook.js:77:14)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at init (C:\..\SFDC-Explorer\node_modules\electron-compile\lib\config-
parser.js:294:16)
    at main (C:\..\SFDC-Explorer\node_modules\electron-prebuilt-compile\li
b\es6-init.js:58:29)


```

Thank you again!

**Comment by datamike** [comment]
@stanlemon So - just for fun - I commented out the lines in main.js that was doing the 'electron.app.setAboutPanelOptions' function call.

Then when I ran start, the electron app loads!  
Now to get my configuration information straightened out:  "error=redirect_uri_mismatch&error_description=redirect_uri%20must%20match%20configuration"

**Comment by stanlemon** [comment]
I'm glad you were able to get it to work! That `electron.app.setAboutPanelOptions` probably needs to be put behind a conditional as it's a macOS thing. I'm happy to do this, or if you'd like to contribute a PR that's cool too.

**Comment by edasque** [comment]
For those on MacOS X having "keytar was compiled against a different Node.js version using" issues, this did the trick: ```npm install --save-dev electron-rebuild
./node_modules/.bin/electron-rebuild```

**Comment by stanlemon** [comment]
I upgraded electron forge and this whole process should be a lot easier now. Also, if you just want to try things out I’ve uploaded a working build to the releases page. Thanks everyone for your comments!
